# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
	  #ensure_git_status_clean
	  #
	  # Increment the build number (not the version number)
	  # Providing the xcodeproj is optional
	  #increment_build_number(xcodeproj: "Gifer.xcodeproj")

	  ## Commit the version bump
	  #commit_version_bump(xcodeproj: "Gifer.xcodeproj")

	  ## Add a git tag for this build. This will automatically
	  ## use an appropriate git tag name
	  #add_git_tag

	  ## Push the new commit and tag back to your git remote
	  #push_to_git_remote
	
	  sync_code_signing
	  disable_automatic_code_signing(path: "Gifer.xcodeproj")
	  build_app(scheme: "Gifer")
	  enable_automatic_code_signing(path: "Gifer.xcodeproj")

	  upload_to_testflight(
		  "skip_waiting_for_build_processing": true,
		  changelog: "Fix some video range selection bugs"
	  )
  end

  lane :tt do
	  #sync_code_signing
	  #disable_automatic_code_signing(path: "Gifer.xcodeproj")
	  sync_code_signing(type: "appstore")
	  build_app(scheme: "Gifer")
	  #enable_automatic_code_signing(path: "Gifer.xcodeproj")
	  upload_to_testflight
  end


  lane :release do
    increment_build_number(xcodeproj: "Gifer.xcodeproj")

    # Commit the version bump
    commit_version_bump(xcodeproj: "Gifer.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote
    #capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "Gifer")
    upload_to_app_store                  # upload your app to App Store Connect
    #slack(message: "Successfully uploaded a new App Store build")
  end

  #desc "Deploy a new version to the App Store"
  #lane :release do
  #  # match(type: "appstore")
  #  # snapshot
  #  gym(scheme: "Gifer") # Build your app - more options available
  #  deliver(force: true)
  #  # frameit
  #end
end
